name: yapper
description: "A new Flutter chat application."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1 
  firebase_storage: ^12.1.0

  # BLoC for State Management
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5


  # File & Audio Handling
  file_picker: ^8.0.3       # For picking any file/media
  audioplayers: ^6.0.0     # For playing voice notes
  
  # Utilities
  uuid: ^4.4.0               # To generate unique IDs for messages/files

  # Functional Programming (for handling failures)
  dartz: ^0.10.1

  # Dependency Injection
  get_it: ^7.7.0
  
  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/