name: yapper
description: "A new Flutter chat application."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  firebase_storage: ^13.0.3

  loading_animation_widget: ^1.2.0

  flutter_launcher_icons: ^0.14.4

  # BLoC for State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5


  # File & Audio Handling
  file_picker: ^10.3.3       # For picking any file/media
  audioplayers: ^6.0.0     # For playing voice notes
  url_launcher: ^6.3.0     # For opening file URLs
  record: ^5.1.0           # For recording audio
  path_provider: ^2.1.4    # For temp file paths
  
  # Utilities
  uuid: ^4.4.0               # To generate unique IDs for messages/files
  cached_network_image: ^3.3.0  # For caching profile images

  # Functional Programming (for handling failures)
  dartz: ^0.10.1

  # Dependency Injection
  get_it: ^8.2.0
  
  # Icons
  cupertino_icons: ^1.0.8
  internet_connection_checker: ^3.0.1
  image_picker: ^1.2.0
  supabase_flutter: ^2.10.3
  shared_preferences: ^2.5.3
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

dependency_overrides:
  record_linux: ^1.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
